# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low




- name: Test for existence /etc/group
  stat:
    path: "/etc/group"
  register: file_exists
  
- name: Ensure permission u-xs,g-xws,o-xwt on /etc/group
  file:
    path: "/etc/group"
    mode: "u-xs,g-xws,o-xwt"
  when: file_exists.stat is defined and file_exists.stat.exists


