# platform = Red Hat Enterprise Linux 8,Red Hat Enterprise Linux 9
# reboot = true
# strategy = configure
# complexity = medium
# disruption = low
- name: Ensure BLS boot entries options contain page_poison=1
  block:

  - name: 'Check how many boot entries exist '
    find:
      paths: /boot/loader/entries/
      patterns: '*.conf'
    register: n_entries

  - name: Check how many boot entries set page_poison=1
    find:
      paths: /boot/loader/entries/
      contains: ^options .*page_poison=1.*$
      patterns: '*.conf'
    register: n_entries_options

  - name: Update boot entries options
    command: grubby --update-kernel=ALL --args="page_poison=1"
    when: n_entries is defined and n_entries_options is defined and n_entries.matched
      != n_entries_options.matched

  - name: Check if /etc/kernel/cmdline exists
    stat:
      path: /etc/kernel/cmdline
    register: cmdline_stat

  - name: Check if /etc/kernel/cmdline contains page_poison=1
    find:
      paths: /etc/kernel/
      patterns: cmdline
      contains: ^.*page_poison=1.*$
    register: cmdline_find

  - name: Add /etc/kernel/cmdline contains page_poison=1
    lineinfile:
      create: true
      path: /etc/kernel/cmdline
      line: page_poison=1
    when: cmdline_stat is defined and not cmdline_stat.stat.exists

  - name: Append /etc/kernel/cmdline contains page_poison=1
    lineinfile:
      path: /etc/kernel/cmdline
      backrefs: true
      regexp: ^(.*)$
      line: \1 page_poison=1
    when: cmdline_stat is defined and cmdline_stat.stat.exists and cmdline_find is
      defined and cmdline_find.matched == 0
  when:
  - ansible_architecture == "s390x"
  - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
  - CCE-84101-5
  - configure_strategy
  - low_disruption
  - medium_complexity
  - medium_severity
  - reboot_required
  - zipl_page_poison_argument
