# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv,multi_platform_sle
# reboot = true
# strategy = restrict
# complexity = medium
# disruption = low


- (xccdf-var var_spec_store_bypass_disable_options)





- name: Check spec_store_bypass_disable argument exists
  command: grep 'GRUB_CMDLINE_LINUX.*spec_store_bypass_disable=' /etc/default/grub
  failed_when: False
  register: argcheck

- name: Replace existing spec_store_bypass_disable argument
  replace:
      path: /etc/default/grub
      regexp: 'spec_store_bypass_disable=\w+'
      replace: 'spec_store_bypass_disable={{ var_spec_store_bypass_disable_options }}'
  when: argcheck.rc == 0

- name: Add spec_store_bypass_disable argument
  replace:
      path: /etc/default/grub
      regexp: '(GRUB_CMDLINE_LINUX=.*)"'
      replace: '\1 spec_store_bypass_disable={{ var_spec_store_bypass_disable_options }}"'
  when: argcheck.rc != 0

- name: Update grub defaults and the bootloader menu
  command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
