# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium

- name: List /etc/sysctl.d/*.conf files

  find:
    paths:
      - "/etc/sysctl.d/"
      - "/run/sysctl.d/"


      - "/usr/lib/sysctl.d/"

    contains: '^[\s]*net.ipv4.conf.all.shared_media.*$'
    patterns: "*.conf"
    file_type: any
  register: find_sysctl_d

- name: Comment out any occurrences of net.ipv4.conf.all.shared_media from config files
  replace:
    path: "{{ item.path }}"
    regexp: '^[\s]*net.ipv4.conf.all.shared_media'
    replace: '#net.ipv4.conf.all.shared_media'
  loop: "{{ find_sysctl_d.files }}"


- name: Comment out any occurrences of net.ipv4.conf.all.shared_media from /etc/sysctl.conf
  replace:
    path: "/etc/sysctl.conf"
    regexp: '^[\s]*net.ipv4.conf.all.shared_media'
    replace: '#net.ipv4.conf.all.shared_media'

- (xccdf-var sysctl_net_ipv4_conf_all_shared_media_value)

- name: Ensure sysctl net.ipv4.conf.all.shared_media is set
  sysctl:
    name: "net.ipv4.conf.all.shared_media"
    value: "{{ sysctl_net_ipv4_conf_all_shared_media_value }}"

    sysctl_file: "/etc/sysctl.d/net_ipv4_conf_all_shared_media.conf"

    state: present
    reload: yes
