# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium

- name: List /etc/sysctl.d/*.conf files
      
  find:
    paths:
      - "/etc/sysctl.d/"
      - "/run/sysctl.d/"
      - "/usr/local/lib/sysctl.d/"


    contains: '^[\s]*net.ipv4.tcp_invalid_ratelimit.*$'
    patterns: "*.conf"
    file_type: any
  register: find_sysctl_d

- name: Comment out any occurrences of net.ipv4.tcp_invalid_ratelimit from config files
  replace:
    path: "{{ item.path }}"
    regexp: '^[\s]*net.ipv4.tcp_invalid_ratelimit'
    replace: '#net.ipv4.tcp_invalid_ratelimit'
  loop: "{{ find_sysctl_d.files }}"


- (xccdf-var sysctl_net_ipv4_tcp_invalid_ratelimit_value)

- name: Ensure sysctl net.ipv4.tcp_invalid_ratelimit is set
  sysctl:
    name: "net.ipv4.tcp_invalid_ratelimit"
    value: "{{ sysctl_net_ipv4_tcp_invalid_ratelimit_value }}"

    sysctl_file: "/etc/sysctl.conf"

    state: present
    reload: yes
