# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv,multi_platform_sle
# reboot = true
# strategy = restrict
# complexity = medium
# disruption = low




- name: Check slab_nomerge argument exists
  command: grep 'GRUB_CMDLINE_LINUX.*slab_nomerge=' /etc/default/grub
  failed_when: False
  register: argcheck

- name: Replace existing slab_nomerge argument
  replace:
      path: /etc/default/grub
      regexp: 'slab_nomerge=\w+'
      replace: 'slab_nomerge=yes'
  when: argcheck.rc == 0

- name: Add slab_nomerge argument
  replace:
      path: /etc/default/grub
      regexp: '(GRUB_CMDLINE_LINUX=.*)"'
      replace: '\1 slab_nomerge=yes"'
  when: argcheck.rc != 0

- name: Update grub defaults and the bootloader menu
  command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
