# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low




- name: Test for existence /boot/grub/grub.cfg
  stat:
    path: "/boot/grub/grub.cfg"
  register: file_exists
  
- name: Ensure permission u-xs,g-xwrs,o-xwrt on /boot/grub/grub.cfg
  file:
    path: "/boot/grub/grub.cfg"
    mode: "u-xs,g-xwrs,o-xwrt"
  when: file_exists.stat is defined and file_exists.stat.exists


