# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low




- name: Test for existence /boot/grub2/user.cfg
  stat:
    path: "/boot/grub2/user.cfg"
  register: file_exists

- name: Ensure owner 0 on /boot/grub2/user.cfg
  file:
    path: "/boot/grub2/user.cfg"
    owner: "0"
  when: file_exists.stat is defined and file_exists.stat.exists


