# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv,SUSE Linux Enterprise 15
# reboot = false
# strategy = enable
# complexity = low
# disruption = low


- (xccdf-var var_zoneminder_anon_write)


- name: Ensure python3-libsemanage installed
  package:
    name: python3-libsemanage
    state: present

- name: Set SELinux boolean zoneminder_anon_write accordingly
  seboolean:
    name: zoneminder_anon_write
    state: "{{ var_zoneminder_anon_write }}"
    persistent: yes
