# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium

- name: List /etc/sysctl.d/*.conf files
      
  find:
    paths:
      - "/etc/sysctl.d/"
      - "/run/sysctl.d/"
      - "/usr/local/lib/sysctl.d/"


    contains: '^[\s]*vm.mmap_min_addr.*$'
    patterns: "*.conf"
    file_type: any
  register: find_sysctl_d

- name: Comment out any occurrences of vm.mmap_min_addr from config files
  replace:
    path: "{{ item.path }}"
    regexp: '^[\s]*vm.mmap_min_addr'
    replace: '#vm.mmap_min_addr'
  loop: "{{ find_sysctl_d.files }}"


- name: Ensure sysctl vm.mmap_min_addr is set to 65536
  sysctl:
    name: "vm.mmap_min_addr"
    value: "65536"

    sysctl_file: "/etc/sysctl.conf"

    state: present
    reload: yes
