# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low




- name: Test for existence /etc/at.allow
  stat:
    path: "/etc/at.allow"
  register: file_exists
  
- name: Ensure permission u-xs,g-xws,o-xwrt on /etc/at.allow
  file:
    path: "/etc/at.allow"
    mode: "u-xs,g-xws,o-xwrt"
  when: file_exists.stat is defined and file_exists.stat.exists


