# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Gather the package facts
  package_facts:
    manager: auto
  tags:
  - NIST-800-53-AC-2(1)
  - accounts_password_pam_enforce_local
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy

- name: Ensure PAM Enforces Password Requirements - Enforce for Local Accounts Only
  lineinfile:
    path: /etc/security/pwquality.conf
    create: true
    line: local_users_only
    state: present
  when: '"pam" in ansible_facts.packages'
  tags:
  - NIST-800-53-AC-2(1)
  - accounts_password_pam_enforce_local
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy
